# Path to your oh-my-zsh installation.
ZSH=$HOME/.oh-my-zsh

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

if [[ -e "$ZSH/custom/okkuz.zsh-theme" ]]; then
  ZSH_THEME="okkuz"
fi

COMPLETION_WAITING_DOTS="true"

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor)

plugins=( \
  zsh-completions \
  zsh-syntax-highlighting \

  # safe-paste \
  extract \
  man-colors \
  catimg \
  nyan \
  tmux-title \

  sublime \
  grunt \
  node \
  redis-cli \
  rsync \
  golang \
  sbt \
  mvn \
  aws \
)

# zsh-users/zsh-completions needs this
autoload -Uz compinit
if [[ "$OSTYPE" = linux* ]] && [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]];
then
  compinit;
else
  compinit -C;
fi;

TERM=xterm-256color

source $ZSH/oh-my-zsh.sh

EDITOR='vim'

# Report anything that takes a while
REPORTTIME=60

if [[ -s $HOME/.dircolors ]]; then
  eval $(dircolors $HOME/.dircolors)
fi

bindkey -v
KEYTIMEOUT=1
bindkey "^[[1~" vi-beginning-of-line   # Home
bindkey "^[[4~" vi-end-of-line         # End
bindkey '^[[2~' beep                   # Insert
bindkey '^[[3~' delete-char            # Del
bindkey '^[[5~' vi-backward-blank-word # Page Up
bindkey '^[[6~' vi-forward-blank-word  # Page Down
bindkey '^[[1;5D' emacs-backward-word  # Ctrl Left
bindkey '^[[1;5C' emacs-forward-word   # Ctrl Right

# alt-enter for multi line
bindkey '^[^M' self-insert-unmeta

alias headset2="a2dp.py A0:E9:DB:4F:1E:EC"
alias ls='ls --group-directories-first --color=tty'
function gg {
  local lolcatarg="-p 10 -S 200"
  echo wat | lolcat -t &> /dev/null
  if [ $? -eq 0 ]; then lolcatarg="${lolcatarg} -t "; fi
  ping google.com | lolcat $(echo $lolcatarg) -
}

alias g='git'
# alias glog="git log --color --graph --abbrev-commit --pretty=format:'%Cred%h%Creset %Cgreen(%cr) -%C(yellow)%d%Creset %s %C(bold blue)<%an>%Creset'"
# alias gloga="git log --oneline --decorate --graph --all --pretty=format:'%Cred%h%Creset %Cgreen(%cr) -%C(yellow)%d%Creset %s %C(bold blue)<%an>%Creset'"

# direnv
if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi

# Set up global NPM packages path with write permissions
NPM_CONFIG_PREFIX="${HOME}/.npm-packages"
if [ -d $NPM_CONFIG_PREFIX ]; then
  mkdir -p ${NPM_CONFIG_PREFIX}/bin

  # Unset manpath so we can inherit from /etc/manpath via the `manpath` command
  unset MANPATH # delete if you already modified MANPATH elsewhere in your config
  MANPATH="$NPM_CONFIG_PREFIX/share/man:$(manpath)"

  # Add NPM bins to path
  PATH="$NPM_CONFIG_PREFIX/bin:$PATH"
fi

# NPM/n related set up
export N_PREFIX=${HOME}/.n
mkdir -p ${N_PREFIX}/bin
PATH=$N_PREFIX/bin:$PATH

# Go path
GOPATH=${HOME}/.go
[ -d $GOPATH ] && PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"

# python
if [ -e ${HOME}/.pyenv/bin/pyenv ]; then
  PATH="${HOME}/.pyenv/bin:$PATH"
  # lazy loading
  pyenv() {
    eval "$(command pyenv init -)"
    eval "$(command pyenv virtualenv-init -)"
    pyenv "$@"
  }
fi

# rust
if [ -e ${HOME}/.cargo/bin ]; then
  PATH="${HOME}/.cargo/bin:$PATH"
fi

# opam/ocaml
if [[ -e "$HOME/.opam/opam-init/init.zsh" ]] then
  "$HOME/.opam/opam-init/init.zsh" > /dev/null 2> /dev/null || true
fi

# ~/bin ~/.local/bin
PATH="${HOME}/bin:${HOME}/.local/bin:$PATH"

# Make $path unique only so I dont fill it up with tmux
typeset -aU path

# https://github.com/robbyrussell/oh-my-zsh/issues/1720
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
# start typing + [Down-Arrow] - fuzzy find history backward
if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi

# ctrl-r invokes incremental backwards search in vi mode
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward

# Search backwards and forwards with a pattern
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward

# set up for insert mode too
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward

unsetopt share_history
unsetopt correct

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
